# Generated by Django 5.2.7 on 2025-11-11 22:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('counselor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='counselorprofile',
            old_name='experience_years',
            new_name='experience',
        ),
        migrations.RemoveField(
            model_name='counselorprofile',
            name='is_active',
        ),
        migrations.AddField(
            model_name='counselorprofile',
            name='available_slots',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='counselorprofile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='counselorprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='counselorprofile',
            name='languages',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='counselorprofile',
            name='qualifications',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='counselorprofile',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='counselorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='counselor_profile', to='accounts.user'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='CounselorSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('prescription', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counselor.counselorprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='accounts.user')),
            ],
        ),
    ]
