# Generated by Django 5.2.7 on 2025-11-16 14:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('counselor', '0002_rename_experience_years_counselorprofile_experience_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counselorprofile',
            name='available_slots',
        ),
        migrations.AddField(
            model_name='appointment',
            name='cancel_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='appointment',
            name='meeting_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='counselorprofile',
            name='specialization',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='counselorsession',
            name='counselor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='counselor.counselorprofile'),
        ),
        migrations.AlterField(
            model_name='counselorsession',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_sessions', to='accounts.user'),
        ),
        migrations.AlterField(
            model_name='message',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='counselor.appointment'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_data', to='counselor.appointment'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='CounselorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='counselor.counselorprofile')),
            ],
            options={
                'ordering': ['day', 'start_time'],
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='counselor.counseloravailability'),
        ),
    ]
