# Generated by Django 5.2.7 on 2025-11-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselor', '0004_counselorprofile_approach_counselorprofile_education_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counselorprofile',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='counselorprofile',
            name='application_status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='counselorprofile',
            name='specialization',
            field=models.CharField(choices=[('academic_stress', 'Academic Stress'), ('anxiety_stress', 'Anxiety & Stress Management'), ('depression', 'Depression Support'), ('career_guidance', 'Career & Academic Guidance'), ('relationship_issues', 'Relationship Issues'), ('self_esteem', 'Self-esteem & Confidence'), ('time_management', 'Time Management & Productivity'), ('behavioral_issues', 'Behavioral Issues'), ('family_issues', 'Family Issues'), ('grief_support', 'Grief & Emotional Healing'), ('trauma_support', 'Trauma Support'), ('mindfulness', 'Mindfulness & Well-being')], max_length=50),
        ),
    ]
