# Generated by Django 5.2.7 on 2025-11-16 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselor', '0005_remove_counselorprofile_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='counselorprofile',
            name='is_applied',
            field=models.BooleanField(default=False),
        ),
    ]
