# Generated by Django 5.2.7 on 2025-11-18 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assist', '0002_alter_chatmessage_user_sessionreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionreport',
            name='summary',
        ),
        migrations.AddField(
            model_name='sessionreport',
            name='summary_json',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
