# Generated by Django 5.2.7 on 2025-11-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assist', '0003_remove_sessionreport_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionreport',
            name='session_name',
            field=models.CharField(default='Untitled Session', max_length=255),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='content',
            field=models.TextField(),
        ),
    ]
