# Generated by Django 5.2.7 on 2025-11-10 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='mood',
            field=models.CharField(choices=[('angry', 'Angry'), ('sad', 'Sad'), ('stressed', 'Stressed'), ('neutral', 'Neutral'), ('calm', 'Calm'), ('joyful', 'Joyful')], max_length=20),
        ),
    ]
