# Generated by Django 5.2.7 on 2025-11-10 21:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('mood', models.CharField(choices=[('very_sad', 'Very Sad'), ('sad', 'Sad'), ('neutral', 'Neutral'), ('happy', 'Happy'), ('very_happy', 'Very Happy')], max_length=20)),
                ('note', models.TextField(default='')),
                ('is_public', models.BooleanField(default=False)),
                ('mood_score', models.PositiveSmallIntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
    ]
