# Generated by Django 5.2.7 on 2025-11-11 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0002_alter_mood_mood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
