# Generated by Django 5.2.7 on 2025-11-11 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('mood', '0003_alter_mood_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMoodSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('avg_score', models.FloatField(default=3.0)),
                ('dominant_mood', models.CharField(choices=[('angry', 'Angry'), ('sad', 'Sad'), ('stressed', 'Stressed'), ('neutral', 'Neutral'), ('calm', 'Calm'), ('joyful', 'Joyful')], max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
    ]
