# Generated by Django 5.2.7 on 2025-11-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselor', '0003_remove_counselorprofile_available_slots_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='counselorprofile',
            name='approach',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='counselorprofile',
            name='education',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='counselorprofile',
            name='motivation',
            field=models.TextField(blank=True, default=''),
        ),
    ]
