# Generated by Django 5.2.7 on 2025-11-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselor', '0006_counselorprofile_is_applied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
