# Generated by Django 5.2.7 on 2025-11-16 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselor', '0007_alter_appointment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counselorprofile',
            name='is_applied',
        ),
        migrations.AddField(
            model_name='counselorprofile',
            name='is_accepted',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='counselorprofile',
            name='application_status',
            field=models.CharField(choices=[('NOT_APPLIED', 'Not Applied'), ('APPLIED', 'Applied')], default='NOT_APPLIED', max_length=20),
        ),
    ]
