# Generated by Django 5.2.7 on 2025-11-16 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counselor', '0008_remove_counselorprofile_is_applied_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='counseloravailability',
            unique_together={('counselor', 'day', 'start_time', 'end_time')},
        ),
    ]
