# Generated by Django 5.2.7 on 2026-03-17 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counselor', '0010_appointmentfeedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CounselorSession',
        ),
    ]
