# Generated by Django 5.2.7 on 2026-03-16 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindfulness', '0003_usermeditationstats_alter_meditationsession_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='meditationsession',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
