# Generated by Django 5.2.7 on 2025-11-11 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('mindfulness', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeditationContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('duration_minutes', models.PositiveSmallIntegerField(default=5)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('is_audio', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='mindfulnesssession',
            options={'ordering': ('-started_at',)},
        ),
        migrations.RemoveField(
            model_name='mindfulnessactivity',
            name='audio_url',
        ),
        migrations.AddField(
            model_name='mindfulnessactivity',
            name='mood_tags',
            field=models.CharField(blank=True, help_text="comma separated mood tags, e.g. 'sad,stressed'", max_length=200),
        ),
        migrations.AlterField(
            model_name='mindfulnessactivity',
            name='activity_type',
            field=models.CharField(choices=[('session_mood', 'Session for Mood'), ('breathing', 'Breathing'), ('body_scan', 'Body Scan'), ('gratitude', 'Gratitude Journal'), ('visualization', 'Visualization'), ('meditation', 'Meditation')], default='session_mood', max_length=50),
        ),
        migrations.AlterField(
            model_name='mindfulnessactivity',
            name='duration_minutes',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='mindfulnessactivity',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='MeditationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveSmallIntegerField(default=0)),
                ('successful', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meditation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mindfulness.meditationcontent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'ordering': ('-started_at',),
            },
        ),
    ]
