# Generated by Django 5.2.7 on 2025-11-11 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('mindfulness', '0002_meditationcontent_alter_mindfulnesssession_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMeditationStats',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.user')),
                ('total_minutes', models.PositiveIntegerField(default=0)),
                ('total_sessions', models.PositiveIntegerField(default=0)),
                ('current_streak', models.PositiveSmallIntegerField(default=0)),
                ('longest_streak', models.PositiveSmallIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='meditationsession',
            options={},
        ),
    ]
